export type ResourceCardProps = {
  id: number;
  collection_color?: string;
  digital_domain: boolean;
  entrepreneurship_domain: boolean;
  green_domain: boolean;
  isGeneratedByAI: boolean;
  description: string;
  creator: (string | null)[];
  title: string;
  media_type: (string | null)[];
  retrieval_date: string | null;
  publication_date: string | null;
  overall_score: number;
  domain?: string[];
  maxHCard?: string;
  maxWCard?: string;
  minWCard?: string;
  minHCard?: string;
  wCard?: string;
  hCard?: string;
  pxCard?: string;
  mbCard?: string;
  ptCardHeader?: string;
  pyCardBody?: string;
  noOfLinesTextCardBody?: number;
  gapGridCardFooter?: number;
  total_likes: number;
  times_used: number;
  assessment_oer_type: string | null;

  //isNormalSizeCard?: boolean;
};
