export type ResourceCardProps = {
  id: number;
  digital_domain: boolean;
  entrepreneurship_domain: boolean;
  green_domain: boolean;
  description: string;
  creator: string[];
  title: string;
  media_type: string[];
  retrieval_date: string;
  overall_score: number;
  domain?: string[];
  maxHCard?: string;
  pxCard?: string;
  mbCard?: string;
  ptCardHeader?: string;
  pyCardBody?: string;
  noOfLinesTextCardBody?: number;
  gapGridCardFooter?: number;
  //isNormalSizeCard?: boolean;
};
