export enum TypeOfActivityStringEnum {
  Open = 'Open Question',
  short_answer_question = 'Short Answer Question',
  true_or_false = 'True or False',
  fill_in_the_blanks = 'Fill in the Blanks',
  multiple_choice = 'Multiple Choice',
  multiple_select = 'Multiple Select',
  essay = 'Essay',
  knowledge_exposition = 'Knowledge Exposition',
  debate = 'Debate',
  brainstorming = 'Brainstorming',
  group_discussion = 'Group Discussion',
  simulation = 'Simulation',
  inquiry_based_learning = 'Inquiry-based Learning',
  non_written_material_analysis = 'Non-written Material Analysis',
  non_written_material_production = 'Non-written Material Production',
  case_study_analysis = 'Case Study Analysis',
  project_based_learning = 'Project-based Learning',
  problem_solving_activity = 'Problem-solving Activity',
}
