import { Flex, Text } from "@chakra-ui/react";
import IconInfoCircle from "../Icons/IconInfoCircle/IconInfoCircle";

type InfoGenAITextBoxProps = {
    isSmallerScreen?: boolean;
}

export default function InfoGenAITextBox({ isSmallerScreen }: InfoGenAITextBoxProps) {
    return (
        <Flex w={isSmallerScreen ? '100%' : '65%'} align='center' gap={3}>
            <IconInfoCircle fontSize={'x-large'} />
            <Text fontSize='small'>
                Keep in mind that the text generated by AI might contain mistakes.
                Make sure to verify the correctness of the generated data before using it in educational contexts.
            </Text>
        </Flex >
    );
}