import InfoTextBox from './InfoTextBox';

type InfoGenAITextBoxProps = {
  isSmallerScreen?: boolean;
};

export default function InfoGenAITextBox({
  isSmallerScreen,
}: InfoGenAITextBoxProps) {
  return (
    <InfoTextBox
      textInfo="Keep in mind that the text generated by AI might contain mistakes. Make
    sure to verify the correctness of the generated data before using it in
    educational contexts."
      isSmallerScreen={isSmallerScreen}
    />
  );
}
