import {
  Box,
  Button,
  Flex,
  HStack,
  Heading,
  Modal,
  ModalBody,
  ModalCloseButton,
  ModalContent,
  ModalFooter,
  ModalHeader,
  ModalOverlay,
  Text,
  Tooltip,
  useDisclosure,
} from '@chakra-ui/react';
import { Dispatch, useEffect, useState } from 'react';

import { useCollectionsContext } from '../../../Contexts/CollectionsContext/CollectionsContext';
import { APIV2 } from '../../../data/api';
import { IconBookmarkCheck } from '../../../public/Icons/svgToIcons/iconBookmarkCheck';
import { IconLunchLinkOpen } from '../../../public/Icons/svgToIcons/iconLunchLinkOpen';
import {
  CollectionProps,
  OerAudienceInfo,
  OerAuthorsInfo,
  OerConceptInfo,
  OerInCollectionProps,
  OerMediaTypeInfo,
  OerProps,
  OerSourceRoerInfo,
  OerSubjectInfo,
  OerUrlInfo,
} from '../../../types/encoreElements';
import { OerFreeSearchProps } from '../../../types/encoreElements/oer/OerFreeSearch';
import { useHasHydrated } from '../../../utils/utils';
import GridMetadataOer from '../../Grids/GridMetadataOer';
import TagConcept from '../../Tags/TagConcept';
import TagResourceType from '../../Tags/TagReourceType';
import TagsDomain from '../../Tags/TagsDomain';
import CollectionModal from '../CollectionModals';
import ExerciseInfoModal from './ExerciseInfoModal';

type CardInfoModalProps = {
  onCardInfoOpen: () => void; // used for the card info modal
  isCardInfoOpen: boolean; // used for the card info modal
  onCardInfoClose: () => void; // used for the card info modal
  oer: OerProps | OerFreeSearchProps | null | undefined;
  updateLikeOER: boolean;
  setUpdateLikeOER: Dispatch<React.SetStateAction<boolean>>;
};

type ColorCollectionProps = {
  name: string;
  color: string | undefined;
};

export default function CardInfoModal({
  oer,
  onCardInfoOpen,
  isCardInfoOpen,
  onCardInfoClose,
  updateLikeOER,
  setUpdateLikeOER,
}: CardInfoModalProps) {
  const { addCollection, addResource, collections, toggleLikeOER, likedOers } =
    useCollectionsContext();
  const hydrated = useHasHydrated();

  const { isOpen, onOpen, onClose } = useDisclosure(); // used for the exercise modal

  const [showTagDigital, setShowTagDigital] = useState<boolean>(false);
  const [showTagEntrepreneurial, setShowTagEntrepreneurial] =
    useState<boolean>(false);
  const [showTagGreen, setShowTagGreen] = useState<boolean>(false);
  const [authors, setAuthors] = useState<(string | null)[]>([]);
  const [linkOer, setLinkOer] = useState<string[]>();
  const [resourceType, setResourceType] = useState<string[]>([]);
  const [subjects, setSubjects] = useState<string[]>([]);
  const [publishers, setPublishers] = useState<(string | null)[]>([]);
  const [contributors, setContributors] = useState<(string | null)[]>([]);
  const [concepts, setConcepts] = useState<string[]>([]);
  const [isAddCollectionModalOpen, setAddCollectionModalOpen] =
    useState<boolean>(false);
  // const [isExerciseModalOpen, setExerciseModalOpen] = useState<boolean>(false);
  const [qualityScore, setQualityScore] = useState<number>(0);
  const [times_used, setTimes_used] = useState<number>(0);
  const [total_likes, setTotal_likes] = useState<number>(0);
  const [lastUpdate, setLastUpdate] = useState<string>('');
  const [description, setDescription] = useState<string>('');
  const [title, setTitle] = useState<string>('');
  const [coverage, setCoverage] = useState<string[]>([]);
  const [source_roer, setSource_roer] = useState<string[]>([]);
  const [collectionsColor, setCollectionsColor] = useState<
    (ColorCollectionProps | undefined)[]
  >([]); // array of colors of the collections that has the oer selected
  // -------------------------
  // variables for the exercise modal
  const [isGeneratedByAI, setIsGeneratedByAI] = useState<boolean>(false); // Check if the exercise is generated by AI
  const [source, setSource] = useState<string>(''); // Source of the generated exercise
  const [language, setLanguage] = useState<string>('');
  const [n_o_d, setN_o_d] = useState<number | null>(null); // Number of Distractors
  const [n_o_w, setN_o_w] = useState<number | null>(null); // Number of Words
  const [n_o_ed, setN_o_ed] = useState<number | null>(null); //Number of Easy Distractor
  const [n_o_ca, setN_o_ca] = useState<number | null>(null); //Number of Correct Answers
  const [type_of_exercise, setType_of_exercise] = useState<string | null>(null); // Type of exercise (is only for the multiple choice question)
  const [type_of_question, setType_of_question] = useState<string | null>(null); // Type of question (is only for the open question)
  const [category, setCategory] = useState<string | null>(null); // Category of the exercise
  const [question, setQuestion] = useState<string | null>(null); // Question of the exercise
  const [question_response, setQuestion_response] = useState<string | null>(
    null
  ); // Response of the question
  const [fill_template, setFill_template] = useState<string | null>(null); // Original text of the exercise
  const [fill_template_with_gaps, setFill_template_with_gaps] = useState<
    string | null
  >(null); // Text with gaps of the exercise
  const [options, setOptions] = useState<string[]>([]); // Options of the multiple choice question
  const [assessment_oer_type, setAssessment_oer_type] = useState<string | null>(
    null
  ); // Type of assessment
  // -------------------------

  const handleViewResource = () => {
    if (linkOer && linkOer[0]) {
      // open the link of the oer
      window?.open(linkOer[0], '_blank');
    } else if (isGeneratedByAI) {
      // open the modal with the exercise
      handleOpenExerciseModal();
    }
  };

  const handleOpenAddCollectionModal = () => {
    setAddCollectionModalOpen(true);
    console.log(isAddCollectionModalOpen);
  };

  const handleCloseCollectionModal = () => {
    setAddCollectionModalOpen(false);
  };

  const handleOpenExerciseModal = () => {
    //setExerciseModalOpen(true);
    onOpen();
    onCardInfoClose();
  };

  const handleCloseExerciseModal = () => {
    //setExerciseModalOpen(false);
    onClose();
    onCardInfoOpen();
  };

  const getCount = async (id: number | undefined) => {
    if (id === undefined) return 0;
    const api = new APIV2(undefined);
    const resp = await api.getCount(id);

    console.log('count: ' + resp);

    return resp;
  };

  const getLikes = async (id: number | undefined) => {
    if (id === undefined) return 0;
    const api = new APIV2(undefined);
    const resp = await api.getLikes(id);

    return resp;
  };

  // const setLikeOER = async (id: number | undefined) => {
  //   if (id === undefined) return;
  //   const api = new APIV2(undefined);
  //   const resp = await api.setLikeOER(id);

  //   setUpdateLikeOER(true);

  //   return resp;
  // };

  // const reduceLikeOER = async (id: number | undefined) => {
  //   if (id === undefined) return;
  //   const api = new APIV2(undefined);
  //   const resp = await api.reduceLikeOER(id);

  //   setUpdateLikeOER(true);

  //   return resp;
  // }

  useEffect(() => {
    const fetchData = async () => {
      try {
        /*setShowTagDigital(false);
              setShowTagEntrepreneurial(false);
              setShowTagGreen(false);
              const domain = oer?.skills?.flatMap((skill: any) =>
                  skill?.domain?.map((item: any) => item.name)
              );
              
              if (domain?.includes(digital)) {
                  setShowTagDigital(true);
              }
              if (domain?.includes(entr)) {
                  setShowTagEntrepreneurial(true);
              }
              if (domain?.includes(green)) {
                  setShowTagGreen(true);
              }*/
        if (oer) {
          setShowTagDigital(oer?.digital_domain || false);
          setShowTagEntrepreneurial(oer?.entrepreneurship_domain || false);
          setShowTagGreen(oer?.green_domain || false);

          setTitle(oer?.title || '');

          const temp_auth = oer.creator?.map(
            (creator_name: OerAuthorsInfo) => creator_name.full_name
          );

          setAuthors(temp_auth?.length !== 0 ? temp_auth : ['Unknown']);

          setLinkOer(oer.oer_url.map((item: OerUrlInfo) => item.url) || []);

          setDescription(oer?.description || '');

          setResourceType(
            oer.media_type?.flatMap(
              (resType: OerMediaTypeInfo) => resType.name
            ) || []
          );

          setSubjects(
            oer.subject?.map((sub: OerSubjectInfo) => sub.name) || ['Unknown']
          );

          setPublishers(
            oer.publisher?.map((pub: OerAuthorsInfo) => pub.full_name) || [
              'Unknown',
            ]
          );
          setContributors(
            oer.contributor?.map(
              (contr: OerAuthorsInfo) => contr.full_name
            ) || ['Unknown']
          );
          setConcepts(
            oer.concepts?.map((concept: OerConceptInfo) => concept.label) || []
          );
          setQualityScore(oer?.overall_score || 0);
          setTimes_used((await getCount(oer?.id)) ?? 0);
          //setTimes_used(oer?.times_used || 0);
          setTotal_likes((await getLikes(oer?.id)) ?? 0);
          //setTotal_likes(oer?.total_likes || 0);
          setLastUpdate(oer?.retrieval_date || oer?.publication_date || '');
          setCoverage(
            oer.coverage?.map((audience: OerAudienceInfo) => audience.name) ||
              []
          );
          setSource_roer(
            oer?.source_roer?.map((item: OerSourceRoerInfo) => item.name) || []
          );

          // set the color of the collections that has the oer selected
          const colors: ColorCollectionProps[] = [];
          collections?.map((collection: CollectionProps) => {
            collection.oers?.map((oer_item: OerInCollectionProps) => {
              if (oer_item.id === oer.id && collection.color !== undefined) {
                //setCollectionsColor((prev: (string | undefined)[]) => [...prev, collection.color]);
                colors.push({ name: collection.name, color: collection.color });
              }
            });
          });

          setCollectionsColor(colors);

          // set the variables for the exercise modal
          setIsGeneratedByAI(oer.generated_by_ai || false);
          setSource(oer.source || '');
          setLanguage(oer.language || '');
          setN_o_d(oer.number_of_distractors || null);
          setN_o_w(oer.number_of_words || null);
          setN_o_ca(oer.number_of_correct_answer || null);
          setN_o_ed(oer.number_of_easy_distractors || null);
          setType_of_exercise(oer.type_of_exercise || null);
          setType_of_question(oer.type_of_question || null);
          setCategory(oer.category || null);
          setQuestion(oer.question || null);
          setQuestion_response(oer.question || null);
          setFill_template(oer.fill_template || null);
          setFill_template_with_gaps(oer.fill_template_with_gaps || null);
          setOptions(oer.options || []);
          setAssessment_oer_type(oer.assessment_oer_type || null);

          /*Promise.all(
            collections?.map(async (collection: CollectionProps) => {
              if (collection.oers?.includes(oer)) {
                return collection.color;
              }
            }) || []
          ).then((colors) => {
            if (!colors.includes(undefined))
              setCollectionsColor(colors);
          });*/
        }
      } catch (error) {
        console.error(error);
      }
    };

    fetchData();
  }, [oer, collections]);

  // gestire rendering dei like dopo che aggiorno il valore
  useEffect(() => {
    if (updateLikeOER) {
      const fetchData = async () => {
        try {
          if (oer !== undefined && oer?.id !== undefined) {
            setTotal_likes((await getLikes(oer?.id)) ?? 0);
          }
        } catch (error) {
          console.error(error);
        } finally {
          setUpdateLikeOER(false);
        }
      };

      fetchData();
    }
  }, [updateLikeOER]);

  /* useEffect(() => {
     console.log('authors: ' + authors);
     console.log('linkOer: ' + linkOer);
     console.log('resourceType: ' + resourceType);
     console.log('subjects: ' + subjects);
     console.log('publishers: ' + publishers);
     console.log('contributors: ' + contributors);
     console.log('concepts: ' + concepts);
   }, [concepts]);*/

  return (
    <Flex>
      <Modal
        isOpen={isCardInfoOpen}
        onClose={onCardInfoClose}
        closeOnOverlayClick={true}
        size={'xl'}
      >
        <ModalOverlay />
        <ModalContent overflow="auto">
          <ModalCloseButton />
          <ModalHeader>
            <HStack pb="5" pr="10">
              <TagsDomain
                showTagDigital={showTagDigital}
                showTagEntrepreneurial={showTagEntrepreneurial}
                showTagGreen={showTagGreen}
                showTagGenAI={isGeneratedByAI}
              />
              {collectionsColor?.length &&
                collectionsColor?.map(
                  (
                    collection_color: ColorCollectionProps | undefined,
                    index: number
                  ) => (
                    <Tooltip
                      key={index}
                      aria-label={collection_color?.name}
                      label={collection_color?.name}
                      hasArrow
                      placement="bottom"
                      bg="gray.200"
                      color="primary"
                      fontSize={'md'}
                      p={2}
                    >
                      <span>
                        <IconBookmarkCheck
                          //key={index}
                          colorBookMark={collection_color?.color}
                          size="25px"
                        />
                      </span>
                    </Tooltip>
                  )
                )}
            </HStack>
            <Heading size="md" mb="5">
              {title}
            </Heading>
            <HStack mb="5">
              <Button
                leftIcon={<IconBookmarkCheck />}
                variant="secondary"
                onClick={(e) => {
                  e.preventDefault();
                  handleOpenAddCollectionModal();
                }}
              >
                Save Resource
              </Button>
              <Tooltip
                label={
                  isGeneratedByAI
                    ? 'View the exercise'
                    : 'View the online resource'
                }
                aria-label={
                  isGeneratedByAI
                    ? 'View the exercise'
                    : 'View the online resource'
                }
                hasArrow
                placement="top"
                bg="gray.300"
                color="primary"
                fontSize={'sm'}
                p={1}
              >
                <Button
                  leftIcon={<IconLunchLinkOpen />}
                  variant="primary"
                  onClick={handleViewResource}
                >
                  View Resource
                </Button>
              </Tooltip>
            </HStack>

            <Flex>
              <Box mr={1}>
                <Text variant="label_drawer">by</Text>
              </Box>
              <Box>
                <Text color="grey" fontWeight="semibold" fontSize="sm">
                  {authors.join(', ')} {/* Print the names with the commas*/}
                </Text>
              </Box>
            </Flex>
          </ModalHeader>
          <ModalBody>
            <Text mb="5">{description}</Text>
            <Flex
              gap={1}
              w="100%"
              pb="5"
              justifyContent={'flex-start'}
              flexWrap={'wrap'}
              flex="1"
            >
              <TagResourceType
                resourceType={
                  assessment_oer_type
                    ? [assessment_oer_type]
                    : resourceType || []
                }
              />
            </Flex>

            <Flex justifyContent={'left'} pb="5" overflowWrap={'normal'}>
              <Box>
                <Text variant="label_drawer">Concepts covered</Text>
                <Flex gap={1} w="100%" flexWrap={'wrap'}>
                  <TagConcept concepts={concepts} />
                </Flex>
              </Box>
            </Flex>
            {collectionsColor?.length > 0 && (
              <Text pb={1} variant="label">
                {' '}
                Click on the like button to let us know if you enjoyed the OER
              </Text>
            )}
            {hydrated && (
              <GridMetadataOer
                gap={3}
                lastUpdate={lastUpdate}
                used={times_used}
                likes={total_likes}
                qualityScore={qualityScore}
                isCardInfoModal={true}
                // setLikeOER={() => setLikeOER(oer?.id)}
                // reduceLikeOER={() => reduceLikeOER(oer?.id)}
                // getLikes={() => getLikes(oer?.id)}
                toggleLikeOER={() => toggleLikeOER(oer?.id)}
                setUpdateLikeOER={setUpdateLikeOER}
                isOERSaved={collectionsColor.length > 0}
                isOERLiked={
                  oer?.id === undefined ? false : likedOers?.includes(oer?.id)
                }
              />
            )}
            <Flex justifyContent={'left'} mb="5">
              <Box>
                <Text variant="label_drawer">Disciplinary field</Text>
                <Text>
                  {' '}
                  {coverage && coverage.length > 0
                    ? coverage.join(', ')
                    : oer?.level}
                </Text>
              </Box>
            </Flex>

            <Flex justifyContent={'flex-start'} mb="5">
              <Box>
                <Text variant="label_drawer">Context</Text>
                <Text>{subjects.join(', ')}</Text>
              </Box>
            </Flex>
            <Flex justifyContent={'left'} mb="5">
              <Box flex="1">
                <Text variant="label_drawer">Publisher</Text>
                <Text>{publishers}</Text>
              </Box>
              <Box flex="1">
                <Text variant="label_drawer">Contributor</Text>
                <Text>{contributors.join(', ')}</Text>
              </Box>
            </Flex>

            {source_roer && source_roer.length > 0 && (
              <Flex justifyContent={'left'} mb="5">
                <Box>
                  <Text variant="label_drawer">Retrieved from</Text>
                  <Text>{source_roer.join(', ')}</Text>
                </Box>
              </Flex>
            )}

            {source && (
              <Flex justifyContent={'left'} mb="5">
                <Box>
                  <Text variant="label_drawer">OER Source</Text>
                  <Text>{source}</Text>
                </Box>
              </Flex>
            )}

            <Flex justifyContent={'left'} mb="5">
              <Box>
                <Text variant="label_drawer">License</Text>
                <Text>{oer?.rights}</Text>
              </Box>
            </Flex>
          </ModalBody>
          <ModalFooter>
            <Button onClick={onCardInfoClose}>Close</Button>
          </ModalFooter>
        </ModalContent>
      </Modal>
      {isAddCollectionModalOpen && (
        <CollectionModal
          isOpen={isCardInfoOpen}
          onClose={handleCloseCollectionModal}
          oerToSave={oer}
          isNewCollection={false}
          isFromFolderButton={false}
          maxLength={30}
          collections={collections}
          addResource={addResource}
          addCollection={addCollection}
          //times_used={times_used}
          //setTimes_used={setTimes_used}
          //getCount={getCount}
        />
      )}
      <ExerciseInfoModal
        isOpen={isOpen}
        onClose={handleCloseExerciseModal}
        //isGeneratedByAI={isGeneratedByAI}
        title={title}
        authors={authors}
        coverage={coverage}
        source={source}
        language={language}
        n_o_d={n_o_d}
        n_o_w={n_o_w}
        n_o_ed={n_o_ed}
        n_o_ca={n_o_ca}
        type_of_exercise={type_of_exercise}
        type_of_question={type_of_question}
        category={category}
        question={question}
        question_response={question_response}
        fill_template={fill_template}
        fill_template_with_gaps={fill_template_with_gaps}
        options={options}
      />
    </Flex>
  );
}
